=== SipT1k/wutheringwaves-app/public/schema/character.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Character",
  "type": "object",
  "properties": {
    "publishedTime": {
      "type": "string"
    },
    "modifiedTime": {
      "type": "string"
    },
    "birthday": { "type": "string" },
    "birthplace": { "type": "string" },
    "quote": { "type": "string" },
    "quoteLocalized": { "type": "object" },
    "description": { "type": "string" },
    "descriptionLocalized": { "type": "object" },
    "stats": {
      "type": "object",
      "properties": {
        "atk": {
          "type": "number"
        },
        "def": {
          "type": "number"
        },
        "hp": {
          "type": "number"
        }
      }
    },
    "skills": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "slug": {
            "type": "string"
          },
          "type": {
            "type": "string",
            "enum": [
              "Basic Attack",
              "Resonance Skill",
              "Resonance Liberation",
              "Inherent Skill",
              "Intro Skill",
              "Outro Skill",
              "Forte Circuit"
            ]
          },
          "name": { "type": "string" },
          "nameLocalized": { "type": "object" },
          "description": { "type": "string" },
          "descriptionLocalized": { "type": "object" }
        },
        "required": ["slug", "type", "name", "description"]
      }
    },
    "ascensions": {
      "type": "array",
      "items": {
        "properties": {
          "cost": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "item": {
                  "type": "integer"
                },
                "quantity": {
                  "type": "integer"
                }
              },
              "required": ["item", "quantity"]
            }
          },
          "minLevel": {
            "type": "integer"
          }
        },
        "required": ["cost", "minLevel"]
      }
    },
    "bestWeapons": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "item": {
            "$ref": "./weapons.components.json#/components/schemas/slug"
          },
          "rank": {
            "type": "integer"
          },
          "different": {
            "type": "number"
          }
        },
        "required": ["item", "rank", "different"]
      }
    },
    "bestEchoSets": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "items": {
            "type": "array",
            "items": {
              "type": "string",
              "$ref": "./echos.schema.json#/components/schemas/sonataEffect"
            },
            "minItems": 1,
            "maxItems": 2
          },
          "different": {
            "type": "number"
          }
        },
        "required": ["items", "different"]
      },
      "minItems": 1
    },
    "bestMainEchoes": {
      "type": "array",
      "items": {
        "type": "string",
        "$ref": "./echos.schema.json#/components/schemas/echoSlug"
      }
    },
    "bestEchoStats": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "enum": ["4-3-3-1-1", "4-4-1-1-1"]
          },
          "name": {
            "type": "string"
          },
          "items": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "cost": {
                  "type": "integer",
                  "maximum": 4,
                  "minimum": 1
                },
                "stats": {
                  "type": "array",
                  "items": {
                    "type": "string",
                    "$ref": "./echo.component.json#/components/schemas/echoMainStat"
                  }
                }
              },
              "required": ["cost", "stats"]
            },
            "minItems": 1,
            "maxItems": 5
          }
        }
      },
      "minItems": 1
    },
    "skillPriority": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "Basic Attack",
          "Resonance Skill",
          "Resonance Liberation",
          "Inherent Skill",
          "Intro Skill",
          "Outro Skill",
          "Forte Circuit"
        ]
      }
    },
    "bestTeams": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "items": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "role": {
                  "type": "string",
                  "$ref": "./characters.schema.json#/components/schemas/characterRole"
                },
                "items": {
                  "type": "array",
                  "items": {
                    "type": "string",
                    "$ref": "./characters.schema.json#/components/schemas/characterSlug"
                  },
                  "minItems": 1
                }
              },
              "required": ["role", "items"]
            }
          }
        },
        "required": ["items"]
      },
      "minItems": 1
    }
  },
  "required": ["publishedTime", "modifiedTime"]
}

=== SipT1k/wutheringwaves-app/resources/characters/zhezhi.json
{
  "$schema": "../../public/schema/character.schema.json",
  "publishedTime": "2024-07-08T11:49:39.662Z",
  "modifiedTime": "2024-07-21T15:18:52.978Z",
  "quote": "What I wanted to say is, the sunlight on you right now is so beautiful. Can I ... paint you?",
  "quoteLocalized": {
    "vi": "Điều tôi muốn nói là, ánh nắng trên bạn lúc này thật đẹp. Tôi có thể... vẽ bạn chứ?"
  },
  "description": "Zhezhi is a commissioned painter, quiet and shy with a dedication to her craft. She's not very eloquent, but her persistence and love for painting speak volumes.",
  "descriptionLocalized": {
    "vi": "Zhezhi là một họa sĩ được ủy thác, im lặng và nhút nhát với sự cống hiến cho đồ nghề của mình. Cô ấy không hùng biện lắm, nhưng sự kiên trì và yêu thích hội họa của cô ấy đã nói lên nhiều."
  },
  "stats": {
    "atk": 375,
    "def": 1198,
    "hp": 12250
  },
  "ascensions": [
    {
      "cost": [{ "item": 2, "quantity": 5000 }],
      "minLevel": 20
    },
    {
      "cost": [
        { "item": 2, "quantity": 10000 },
        { "item": 41300005, "quantity": 1 },
        { "item": 42300050, "quantity": 4 },
        { "item": 41400074, "quantity": 3 }
      ],
      "minLevel": 40
    },
    {
      "cost": [
        { "item": 2, "quantity": 15000 },
        { "item": 41300005, "quantity": 1 },
        { "item": 42300050, "quantity": 8 },
        { "item": 41400074, "quantity": 6 }
      ],
      "minLevel": 50
    },
    {
      "cost": [
        { "item": 2, "quantity": 20000 },
        { "item": 41300005, "quantity": 1 },
        { "item": 42300050, "quantity": 12 },
        { "item": 41400074, "quantity": 9 }
      ],
      "minLevel": 60
    },
    {
      "cost": [
        { "item": 2, "quantity": 40000 },
        { "item": 41300005, "quantity": 1 },
        { "item": 42300050, "quantity": 16 },
        { "item": 41400074, "quantity": 12 }
      ],
      "minLevel": 70
    },
    {
      "cost": [
        { "item": 2, "quantity": 80000 },
        { "item": 41300005, "quantity": 1 },
        { "item": 42300050, "quantity": 20 },
        { "item": 41400074, "quantity": 16 }
      ],
      "minLevel": 80
    }
  ]
}
